# Generated by Django 4.1.7 on 2023-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('lid', models.CharField(max_length=200)),
                ('uidimg', models.ImageField(upload_to='')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('nic', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('log', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('ownership', models.CharField(max_length=200)),
                ('rf_ir', models.CharField(max_length=200)),
                ('soil', models.CharField(max_length=200)),
            ],
        ),
    ]
