# Generated by Django 4.1.7 on 2023-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('mid', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=200)),
                ('machine_type', models.CharField(max_length=200)),
                ('mark', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('date_of_purches', models.DateField()),
                ('year_of_manufacture', models.CharField(max_length=200)),
                ('country_of_origine', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('owner', models.CharField(max_length=200)),
                ('owner_contact', models.CharField(max_length=200)),
            ],
        ),
    ]
